/***************************
 FINAL VERSION
 *************************/

package textfilecompare;

import javax.swing.JFileChooser;
import java.io.*;

public class TextFileCompare extends javax.swing.JFrame {

  String filePath1;
    String filePath2;
    String word1;
    String word2;
    
    char[] charArray;
    int number = 0;  //optional 0 - full words
    int loop; 
    boolean caseSensitive = false;
    int wordsCounter;
    int sameWordsCounter;
    double compliance;
  
    final JFileChooser fc = new JFileChooser();
    
 FileReader fr1 = null;
 FileReader fr2 = null;
 String s1 = "";
 String s2 = "";
 
 String[] array1;
 String[] array2;
 String delimiter ="\\s+";
    
    void display() {
        System.out.println(this.filePath1);
        System.out.println(this.filePath2);
        
    }
    
    //tolerance
    int setNumber(int number) {
    this.number = number;    
    return number;    
    }
    
    boolean setLetterSize(boolean caseSensitive) {
    this.caseSensitive = caseSensitive;
    return caseSensitive;
    }
    
    void resetCounters() {
    this.wordsCounter = 0;
    this.sameWordsCounter = 0;
    }
    
    String firstWord (String word1) {
    if (number==0){loop=word1.length();}
    else {loop=number;}
    this.charArray = word1.toCharArray();
    if (number>word1.length()) {loop=word1.length();}
    word1="";
    for (int i = 0; i<loop; i++) {
       
    word1+=charArray[i];
    }
    if (caseSensitive==false){word1=word1.toLowerCase();}
    return word1;  
    }
    
    String secondWord (String word2) {
    if (number==0){loop=word2.length();}
    else {loop=number;}    
    this.charArray = word2.toCharArray();
    if (number>word2.length()) {loop=word2.length();}
    word2="";
    for (int i = 0; i<loop; i++) {
    word2+=charArray[i];
    }
    if (caseSensitive==false){word2=word2.toLowerCase();}
        return word2; 
    }    
    
    
    public TextFileCompare() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * ARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        wynik = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text FIle Compare");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tolerance");

        jCheckBox1.setText("Case sensitive");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        start.setText("START");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jLabel2.setText("Path 1:");

        jLabel3.setText("Path 2:");

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("jButton2");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        wynik.setColumns(20);
        wynik.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        wynik.setRows(5);
        wynik.setBorder(null);
        jScrollPane1.setViewportView(wynik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(start)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       Object obj = jComboBox1.getSelectedItem();
       this.number = Integer.parseInt(obj.toString());
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()==true) {
        this.caseSensitive = true;
        }
        else {
        this.caseSensitive = false;
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    int returnVal = fc.showOpenDialog(null);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
    this.filePath1 = fc.getSelectedFile().toString();
    jTextField1.setText(this.filePath1);
    }//GEN-LAST:event_jButton2MouseClicked
    }
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    int returnVal = fc.showOpenDialog(null);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
    this.filePath2 = fc.getSelectedFile().toString();
    jTextField2.setText(this.filePath2);
    }//GEN-LAST:event_jButton3MouseClicked
    }
    
    
    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
     try {
        fr1 = new FileReader(filePath1);
        fr2 = new FileReader(filePath2);

      
      BufferedReader br1 = new BufferedReader(fr1);
      BufferedReader br2 = new BufferedReader(fr2);

    
   while(((s1 = br1.readLine()) !=null) && ((s2 = br2.readLine()) != null)){
        
        array1 = s1.split(delimiter);
        array2 = s2.split(delimiter);
        if (array1.length==array2.length){}
        
        // if the number of words in the loaded lines in the files being compared are not equal to, add the words, 
        // which do not correspond to compare to counter these comparisons, we will treat this as a negative result of compare
        else {
         
         int lineWordsCounter;
         lineWordsCounter = (array1.length-1)-(array2.length-1);
         if (lineWordsCounter<0){lineWordsCounter*=-1;}
         //System.out.println("Different words:"+lineWordsCounter);
         wordsCounter+=lineWordsCounter;
                }
  for(int i =0; i < array1.length && i < array2.length; i++) {
     // if (array1[i].equals(array2[i])) {System.out.print(i+1+" word - Identical:");}
     // else {System.out.print(i+1+" word - Different:");}
     // System.out.println(array1[i]+"-"+array2[i]);
           word1 = firstWord(array1[i]);
           word2 = secondWord(array2[i]);
           
           if (word1.equals(word2)) {
             //System.out.print(i+1+" word - Identical:");
             wordsCounter+=1;
             sameWordsCounter+=1;
                                          }
        else {
           //System.out.print(i+1+" word - Different:");
             wordsCounter+=1;
             }
             
          
           //System.out.println(kp.word1+"-"+kp.word2);
       }
      //System.out.print("Compare in file: "+kp.wordsCounter+" ");
      //kp.compliance =(((double)kp.sameWordsCounter/(double)kp.wordsCounter)*100);
      //System.out.println("Zgodnosc:"+kp.compliance+"%");
      //kp.resetCounters();
      }
   
      String newline = "\n";
      wynik.append("Compare in file: "+wordsCounter+newline);
      compliance =(((double)sameWordsCounter/(double)wordsCounter)*100);
      int round = (int)(compliance*100.0);
      compliance = ((double)round)/100;
      wynik.append("Compliance: "+compliance+"%"+newline);
      br1.close();
      br2.close();
      resetCounters();

    } catch (FileNotFoundException e) {
      e.printStackTrace();
    } catch (IOException e) {
      e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_startMouseClicked

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed
    
  
    public static void main(String args[]) {
     
TextFileCompare kp = new TextFileCompare();

java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextFileCompare().setVisible(true);
              
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton start;
    private javax.swing.JTextArea wynik;
    // End of variables declaration//GEN-END:variables
}
